language: python
python:
  - "3.8"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=varlib -m py.test
after_success:
  - coveralls
sudo: false
